package com.sifu.trainingui.model

import com.sifu.trainingui.components.utils.BottomSheetState

val PurposeModel = listOf(
    BottomSheetState(
        phoneNumber = "",
        subTitle = "Pay for goods and services",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
    BottomSheetState(
        phoneNumber = "",
        subTitle = "Loan Repayment",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
    BottomSheetState(
        phoneNumber = "",
        subTitle = "Credit Card Payment",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
    BottomSheetState(
        phoneNumber = "",
        subTitle = "School Fees",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
    BottomSheetState(
        phoneNumber = "",
        subTitle = "Rental Fees",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
    BottomSheetState(
        phoneNumber = "",
        subTitle = "Lending",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
    BottomSheetState(
        phoneNumber = "",
        subTitle = "Travel Expenses",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
    BottomSheetState(
        phoneNumber = "",
        subTitle = "Buy Property",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
    BottomSheetState(
        phoneNumber = "",
        subTitle = "Buy Property",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
    BottomSheetState(
        phoneNumber = "",
        subTitle = "Buy Property",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
    BottomSheetState(
        phoneNumber = "",
        subTitle = "Buy Property",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
    BottomSheetState(
        phoneNumber = "",
        subTitle = "Buy Property",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
    BottomSheetState(
        phoneNumber = "",
        subTitle = "Buy Property",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
    BottomSheetState(
        phoneNumber = "",
        subTitle = "Buy Property",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
    BottomSheetState(
        phoneNumber = "",
        subTitle = "Buy Property",
        currency = " ",
        amount = " ",
        onSelect = {},
    ),
)